spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: journaldb
      auto-index-creation: true

  redis:
    host: ${REDIS_HOST}
    port: 16834
    password: ${REDIS_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: dummy@gmail.com
    password: dummy
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
